In [3]:
from google.colab import drive
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
import pandas as pd
import pickle

In [4]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
data = []

In [6]:
with open('/content/gdrive/MyDrive/Pranav WiDes Data/Data Processing/new_paths_output/path_bld01_tx001_output.pkl', 'rb') as file:
        data = pickle.load(file)

print(data[-1])

[[[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.329669e+02  2.808500e-06  2.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.332549e+02  2.808100e-06  1.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.747940e+02  3.419500e-06  4.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.803680e+02  3.804100e-06  4.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.848872e+02  3.769700e-06  3.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.872438e+02  3.288100e-06  5.000000e+00]]

 [[ 5.121087e+01  5.621931e+02  3.857083e+00]
  [ 8.485697e+02  8.270031e+02  6.370828e-01]
  [-1.886211e+02  3.988500e-06  3.000000e+00]]

 [[ 5.121087e+01  5.

In [7]:
len(data)

29929

In [8]:
len(data[0])

45

In [9]:
Tx_position = data[0][0][0]

In [10]:
Tx_position


array([ 51.21087 , 562.1931  ,   3.857083])

In [11]:
len(data[29235]), data[29235]

(3,
 array([[[ 5.121087e+01,  5.621931e+02,  3.857083e+00],
         [ 8.435697e+02,  8.070031e+02,  6.370828e-01],
         [-1.801091e+02,  3.736700e-06,  4.000000e+00]],
 
        [[ 5.121087e+01,  5.621931e+02,  3.857083e+00],
         [ 8.435697e+02,  8.070031e+02,  6.370828e-01],
         [-1.943154e+02,  3.808700e-06,  6.000000e+00]],
 
        [[ 5.121087e+01,  5.621931e+02,  3.857083e+00],
         [ 8.435697e+02,  8.070031e+02,  6.370828e-01],
         [-2.172990e+02,  3.776300e-06,  5.000000e+00]]]))

In [12]:
Rx_position = []

In [13]:
for i in range(len(data)):
  if data[i].size != 0:
    # print(data[i][0][1])
    Rx_position.append(data[i][0][1])
  else:
    Rx_position.append([])                            #can be removed if we are okay with less than 29929 Rx_positions
len(Rx_position)

29929

In [14]:
Rx_position

[array([-11.43029  , -32.99686  ,   0.6370828]),
 array([ -6.430288 , -32.99686  ,   0.6370828]),
 array([ -1.430288 , -32.99686  ,   0.6370828]),
 array([  3.569712 , -32.99686  ,   0.6370828]),
 array([  8.569712 , -32.99686  ,   0.6370828]),
 array([ 13.56971  , -32.99686  ,   0.6370828]),
 array([ 18.56971  , -32.99686  ,   0.6370828]),
 array([ 23.5697   , -32.99686  ,   0.6370828]),
 array([ 28.5697   , -32.99686  ,   0.6370828]),
 array([ 33.5697   , -32.99686  ,   0.6370828]),
 array([ 38.5697   , -32.99686  ,   0.6370828]),
 array([ 43.5697   , -32.99686  ,   0.6370828]),
 array([ 48.5697   , -32.99686  ,   0.6370828]),
 array([ 53.5697   , -32.99686  ,   0.6370828]),
 array([ 58.5697   , -32.99686  ,   0.6370828]),
 array([ 63.5697   , -32.99686  ,   0.6370828]),
 array([ 68.56969  , -32.99686  ,   0.6370828]),
 array([ 73.56969  , -32.99686  ,   0.6370828]),
 array([ 78.56969  , -32.99686  ,   0.6370828]),
 array([ 83.56969  , -32.99686  ,   0.6370828]),
 array([ 88.56969  ,

In [ ]:
power = []

In [ ]:
for i in range(len(data)):
  tmp = []
  if data[i].size != 0:                             #change identation of power.append and change pos of tmp = [] to make len less than 29929
    for j in range(len(data[i])):
      tmp.append(data[i][j][2][0])
  power.append(tmp)

In [ ]:
power[1000]

[]

In [ ]:
for i in power:
  if len(i) != 0 :
    # print(len(i))
    pass

In [ ]:
len(power[0]), len(power[1]), power[0]

(45,
 45,
 [-95.9477,
  -96.4262,
  -106.1572,
  -106.1946,
  -126.0117,
  -126.1789,
  -128.6675,
  -129.1148,
  -129.7411,
  -130.2611,
  -130.6968,
  -131.1154,
  -131.6396,
  -131.8846,
  -132.4561,
  -132.5603,
  -134.2742,
  -135.1354,
  -135.5771,
  -135.6927,
  -135.775,
  -137.0195,
  -138.4834,
  -138.863,
  -138.9864,
  -139.0062,
  -139.2512,
  -139.346,
  -139.9926,
  -140.4283,
  -140.8004,
  -142.1549,
  -142.603,
  -144.535,
  -144.9894,
  -146.3785,
  -146.8307,
  -147.0815,
  -147.6414,
  -148.0205,
  -148.2411,
  -148.3552,
  -148.8491,
  -149.3259,
  -149.6514])