In [ ]:
from google.colab import drive
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
import pandas as pd

In [ ]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
with open('/content/gdrive/MyDrive/Pranav WiDes Data/Data Processing/new_paths_output/path_bld01_tx001_output.txt', 'r') as file:
        data = file.read()
print(data[-1])

OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/Pranav WiDes Data/Data Processing/new_paths_output/path_bld01_tx001_output.txt'

In [ ]:
print(data)

In [ ]:
data = np.load('/content/gdrive/MyDrive/Pranav WiDes Data/Data Processing/Output Files/Copy of path_bld01_tx001_ouput.npz')['data']
data, data.shape


Pi, delay = [data[i, j, 2, 0] for i in range(29929) for j in range(45)], [data[i, j, 2, 1] for i in range(29929) for j in range(45)]
Pi = np.array(Pi)
delay = np.array(delay)

is_nan_plus_0j = np.isnan(Pi.real) & (Pi.imag == 0)
Pi[is_nan_plus_0j] = 0 + 0j

is_nan_plus_0j = np.isnan(delay.real) & (delay.imag == 0)
delay[is_nan_plus_0j] = 0 + 0j

delay.shape, Pi.shape




((1346805,), (1346805,))

In [ ]:
theta = np.random.uniform(0, np.pi, (1346805,))
theta, theta.shape

(array([2.61504365e+00, 2.19798965e+00, 2.00028397e+00, ...,
        2.22509711e+00, 3.96727400e-01, 1.65043934e-03]),
 (1346805,))

In [ ]:
power = 10 ** ((Pi - 30) / 20)
power, power.shape

(array([ 2.97286161e+02-1788.31111842j,  1.24509254e+02+1887.39068987j,
        -1.91200604e+03+2561.9341199j , ...,
         3.16227766e-02   +0.j        ,  3.16227766e-02   +0.j        ,
         3.16227766e-02   +0.j        ]),
 (1346805,))

In [ ]:
comp = np.zeros((1346805, ), dtype=np.complex128)
comp = np.exp(1j * theta)
power = power * comp
power

array([ 1.77988699e+03-3.44148232e+02j, -1.83134580e+03+4.73200529e+02j,
        3.07645711e+03+8.68726176e+02j, ...,
       -8.89386823e-03+3.03463195e-02j,  2.76524682e-02-1.53408279e-02j,
        3.11741954e-02+5.30749832e-03j])

In [ ]:
M = 200
bw = 400
freq = np.linspace(-bw/2, bw/2 - bw/M, M)
freq_2d = freq[:, np.newaxis]
freq_2d[0]

array([-200.])

In [1]:
h = np.exp(1j * 2 * np.pi * freq_2d * delay)
a = power * h
a

NameError: name 'np' is not defined

In [ ]:
a.shape

(200, 1346805)

In [ ]:
data = np.load('/content/gdrive/MyDrive/Pranav WiDes Data/Data Processing/Output Files/Copy of path_bld01_tx001_ouput.npz')['data']
data, data.shape
data[0,0,0]

array([ 51.21087 +0.j, 562.1931  +0.j,   3.857083+0.j])

In [ ]:
values_to_extract = np.zeros((29929, 45, 2), dtype=np.complex128)
values_to_extract[:, :, 0] = data[:, :, 2, 0]  # Extract values at position [2, 0]
values_to_extract[:, :, 1] = data[:, :, 2, 1]



In [ ]:
values_to_extract[np.isnan(values_to_extract)] = 0 + 0.j

values_to_extract.shape

(29929, 45, 2)

In [ ]:
theta = np.random.uniform(0, np.pi, (29929,45))
theta.shape

(29929, 45)

In [ ]:
Pi = values_to_extract[:, :, 0]
delay = values_to_extract[:, :, 1]
power = 10 ** ((Pi - 30) / 20)

# print(power)
power.shape

(29929, 45)

In [ ]:
comp = np.zeros((29929,45 ), dtype=np.complex128)

comp = np.exp(1j * theta)

power = power * comp
power.shape

(29929, 45)

In [ ]:
M = 200
bw = 400
freq = np.linspace(-bw/2, bw/2 - bw/M, M)
freq_reshaped = freq.reshape(200, 1, 1)
freq.shape, freq_reshaped.shape


((200,), (200, 1, 1))

In [ ]:
h = np.exp(1j * 2 * np.pi * freq_reshaped * delay)
a = power * h
a.shape

(200, 29929, 45)

In [ ]:
a[0:10,0,0:3]

array([[  391.80685193-1770.00652776j, -1526.23742664-1117.29382347j,
        -1504.10994819-2820.80251099j],
       [  391.85125463-1769.99669825j, -1526.20939465-1117.33211452j,
        -1504.03917374-2820.84024824j],
       [  391.89565708-1769.98686761j, -1526.18136169-1117.37040487j,
        -1503.96839834-2820.87798372j],
       [  391.94005928-1769.97703586j, -1526.15332777-1117.40869452j,
        -1503.897622  -2820.91571742j],
       [  391.98446123-1769.967203j  , -1526.1252929 -1117.44698346j,
        -1503.8268447 -2820.95344935j],
       [  392.02886294-1769.95736903j, -1526.09725706-1117.4852717j ,
        -1503.75606647-2820.9911795j ],
       [  392.07326441-1769.94753394j, -1526.06922026-1117.52355923j,
        -1503.68528728-2821.02890788j],
       [  392.11766562-1769.93769773j, -1526.0411825 -1117.56184606j,
        -1503.61450715-2821.06663448j],
       [  392.16206659-1769.92786042j, -1526.01314378-1117.60013219j,
        -1503.54372607-2821.1043593j ],
       [  